Arreglando los controladores
omegaodin34/Mi_Api_1.0 pull request #2
Opened 2021-08-22 15:37 UTC by omegaodin34

2021-09-10 16:55 UTC, jaltamir requested changes
Jose, quita el renderizado de twig de conference. A día de hoy la API tiene un endpoint de healthcheck.

2021-09-10 16:55 UTC, jaltamir commented on src/Controller/ConferenceServController.php
> +    #[Route('/conference/serv', name: 'conference_serv')]
La ruta ya la tienes definida en el routes.yaml. No te hace falta estas anotaciones para definirlas

2021-09-10 16:55 UTC, jaltamir commented on src/Controller/ConferenceServController.php
> +    #[Route('/', name: 'homepage')]
Esto sobra tb

2021-09-10 16:55 UTC, jaltamir commented on src/Controller/HealthCheckController.php
> +    }
Sobran lineas en blanco y la ultima llave cierra en la primera columna de la línea

2021-09-10 16:55 UTC, jaltamir commented on src/Services/ConferenceServ.php
> +
Intuyo que has hecho una ruta de healthcheck para conference. Eso no es necesario, las API's tienen un único healthcheck para toda la API, en general, y ya lo tienes definido con el endpoint de healthcheck

2021-09-10 16:55 UTC, jaltamir commented on templates/conference_serv/index.html.twig
> +<!DOCTYPE html>
Cuidado con el código que busques. Aquí tienes una plantilla twig, que renderiza html, y tu estás construyendo una API rest que sólo devuelve json.

2021-09-10 16:55 UTC, jaltamir commented on src/Controller/ConferenceServController.php
> +        return $this->render('conference_serv/index.html.twig', [
Aquí estás usando una plantilla twig. Estás devolviendo html y tu estás construyendo una API rest.

2021-09-13 10:34 UTC, omegaodin34 commented on src/Services/ConferenceServ.php
> +
Este esta eliminado ya

2021-09-13 10:54 UTC, omegaodin34 commented on src/Controller/ConferenceServController.php
> +    #[Route('/conference/serv', name: 'conference_serv')]
ya tengo eliminado el renderizado primo
y he quitado las anotaciones, que como tu dices no hace falta al tener los endpoints.
esta eliminado y sigue funcionando. Solo he dejado 2 endpoints, el de healtcheck y el de conference. el de conference me devuelve la lista de libros en json.

health_check:
    path: /check
    controller: App\Controller\HealthCheckController::index
    methods: [GET]
list_book:
    path: books
    controller: App\Controller\ConferenceServController::listBook
    methods: [GET]

2021-09-13 10:56 UTC, omegaodin34 commented on src/Controller/ConferenceServController.php
> +    #[Route('/', name: 'homepage')]
Arreglado también.

2021-09-13 10:57 UTC, omegaodin34 commented on src/Controller/HealthCheckController.php
> +    }
esos espacios también esta arreglado

2021-09-13 10:58 UTC, omegaodin34 commented on src/Services/ConferenceServ.php
> +
he modificado el conference serv y el endpoint para que me devuelva una lista de libros en json.

2021-09-13 10:59 UTC, omegaodin34 commented on templates/conference_serv/index.html.twig
> +<!DOCTYPE html>
las plantillas twig las quitare entonces.

2021-09-13 10:59 UTC, omegaodin34 commented on src/Controller/ConferenceServController.php
> +        return $this->render('conference_serv/index.html.twig', [
Arreglado primo.

2021-09-14 07:56 UTC, jaltamir requested changes

2021-09-14 07:56 UTC, jaltamir commented on templates/conference_serv/index.html.twig
> +<!DOCTYPE html>
Te falta quitar esto.

2021-09-14 07:56 UTC, jaltamir commented on src/Controller/TallerController.php
> +        ]);
Aquí sigues usando twig

2021-09-14 09:34 UTC, closed without merging