First Endpoint, find book by register id
omegaodin34/Mi_Api_1.0 pull request #6
Opened 2021-09-19 22:08 UTC by omegaodin34

2021-09-19 22:19 UTC, jaltamir requested changes
Has modificado el endpoint del listado para mostrar el último disponible. Eso no es lo que había que hacer.

Para crear el endpoint tienes que definir la ruta, luego crear el action en el controlador, y luego ahí usar los servicios que necesites para generar tu respuesta.

La petición GET de /book se queda tal cual. Es el listado y estaba funcionando.

Como hablamos te pido un endpoint distinto. GET de /book/BOOK_ID. Una petición real sería /book/1 y eso me tiene que devolver el libro con el id 1.

A por ello.

2021-09-19 22:19 UTC, jaltamir commented on composer.json
> +    "easycorp/easyadmin-bundle": "^3",
has dejado easy admin instalado. Quita esta línea de composer y ejecuta composer update

2021-09-19 22:19 UTC, jaltamir commented on config/bundles.php
> +    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
esta línea tendrás que quitarla

2021-09-19 22:19 UTC, jaltamir commented on src/Services/BookService.php
> +        $numberOfRegister= 2;
Esto no me lo hagas!!

2021-09-19 22:19 UTC, jaltamir commented on src/Services/BookService.php
> +            $booksResponse[$numberOfRegister] = [
Con esta línea y con $numberOfRegister fijo a 2, te acabas de cargar el listado

El bucle, que lee dos registros, los mete siempre en la posición 2 del array (la tercera posición puesto que se empieza en 0)

2021-09-19 22:19 UTC, jaltamir commented on symfony.lock
> +    },
Esto irá fuera automáticamente cuando actulices las dependencias

2021-09-29 22:13 UTC, jaltamir requested changes

2021-09-29 22:13 UTC, jaltamir commented on composer.json
> +    "easycorp/easyadmin-bundle": "^3",
Tienes que ejecutar composer remove easycorp/easyadmin-bundle

2021-09-29 22:13 UTC, jaltamir commented on config/routes.yaml
> +    type: annotation
Esto tienes que quitarlo. Las rutas sólo en el routes.yaml

2021-09-29 22:13 UTC, jaltamir commented on src/Controller/LibraryController.php
> +
Esta linea sobra

2021-09-29 22:13 UTC, jaltamir commented on src/Controller/LibraryController.php
> +
Y esta

2021-09-29 22:13 UTC, jaltamir commented on src/Controller/LibraryController.php
> +
y esta

2021-09-29 22:13 UTC, jaltamir commented on src/Entity/Book.php
> +    public function getId(): ?string
el id es numérico. Así que getId tiene que devolver un int

2021-09-29 22:13 UTC, jaltamir commented on src/Entity/Book.php
> +    }
El método setId no te es necesario. Borralo

2021-09-29 22:25 UTC, omegaodin34 commented on src/Entity/Book.php
> +    }
listo

2021-09-29 22:26 UTC, omegaodin34 commented on src/Entity/Book.php
> +    public function getId(): ?string
listo

2021-09-29 22:37 UTC, omegaodin34 commented on composer.json
> +    "easycorp/easyadmin-bundle": "^3",
listo

2021-09-29 22:39 UTC, omegaodin34 commented on config/bundles.php
> +    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
listo

2021-09-29 22:46 UTC, merged